/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sirh;

import controller.ControllerReservasi;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import usu.widget.Label;
import usu.widget.TextArea;
import usu.widget.TextBox;

/**
 *
 * @author usernames
 */
public class Guest extends javax.swing.JFrame {
    
   private boolean viaTransfer  = false;
   private boolean viaCredit    = false; 
   
   //for debugging purpose
   private int stockPresidential = 10;
   private int stockDeluxe = 11;   
   private int presidentialChoosed;
   private int deluxeChoosed;
   
   private int pricePresidential = 2000000;
   private int priceDeluxe = 1000000;
   private int totalPriceDetails;
   
   private String firstName;
   private String lastName;
   private String email;
   private String checkInDate;
   private String checkOutDate;
   
   private ArrayList<String> bookedRoom = new ArrayList<String>();  
   
   private int regNo;   
   
   ControllerReservasi controllerReservasi;
    
    public Guest() {        
        initComponents();        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        pack();
        controllerReservasi = new ControllerReservasi(this);
    }
    
    /** PANEL INSERT RESERVASI **/

    public TextBox getTxtIdTamu(){
        return tbNoId;
    }
    
    public JLabel getTxtJmlRoomType1(){
        return lblNumberOfDeluxe;
    }
    
    public JLabel getTxtJmlRoomType2(){
        return lblNumberOfPresidential;
    }
    
    public TextArea getTxtFasilitasTambahan(){
        return taSpcRequest;
    }
    
    public Label getTxtTglMasuk(){
        return lblCheckin;
    }
    
    public Label getTxtTglKeluar(){
        return lblCheckout;
    }
    
    public JLabel getTxtHarga(){
        return lblTotalPrice;
    }
    
    public JLabel getTxtTotalHarga(){
        return lblTotalPrice;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1000, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/StRegisSuperior_Room.resized.resized.jpg"))); // NOI18N
        Background.setPreferredSize(new java.awt.Dimension(550, 369));
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext1ActionPerformed
        if (jDateChooser1.getDate()== null) {//          
           JOptionPane.showMessageDialog(null, "Please pick the date you check-in");
        } else {
            if(stockPresidential==0 && stockDeluxe==0){
                jPanelSlider.nextPanel(10, panelNoRoom, jPanelSlider.left);          
            } else {
                if(stockPresidential==0){
                    panelPresidential.setVisible(false);
                } else {                    
                    panelPresidential.setVisible(true);
                }
                if(stockDeluxe==0){
                    panelDeluxe.setVisible(false);
                } else {                    
                    panelDeluxe.setVisible(true);
                }
                jSpinnerNumberPresidential.setModel(new javax.swing.SpinnerNumberModel(0,0,stockPresidential,1));
                jSpinnerNumberDeluxe.setModel(new javax.swing.SpinnerNumberModel(0,0,stockDeluxe,1));
                lblStockPresidential.setText(String.valueOf(stockPresidential));
                lblStockDeluxe.setText(String.valueOf(stockDeluxe));
                jPanelSlider.nextPanel(10, panel2, jPanelSlider.left);  
            }            
        }
    }//GEN-LAST:event_btnNext1ActionPerformed
    
    private void btnPrev2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrev2ActionPerformed
        jPanelSlider.nextPanel(10, panel1, jPanelSlider.right);
    }//GEN-LAST:event_btnPrev2ActionPerformed

    private void btnNext2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext2ActionPerformed
        presidentialChoosed = (int)jSpinnerNumberPresidential.getValue();
        deluxeChoosed = (int)jSpinnerNumberDeluxe.getValue();
        if (presidentialChoosed==0 && deluxeChoosed==0) {
            JOptionPane.showMessageDialog(null, "Please select at least one room");
        } else {
            int totalPresidentialPrice = (int) jSpinnerNumberPresidential.getValue() * pricePresidential;
            int totalDeluxePrice = (int) jSpinnerNumberDeluxe.getValue() * priceDeluxe;
            totalPriceDetails = totalPresidentialPrice + totalDeluxePrice;
//            bookedRoom.add(email)
            
            lblNumberOfPresidential.setText(String.valueOf(presidentialChoosed));
            lblTotalPresidentialPrice.setText(String.valueOf(totalPresidentialPrice));
            lblNumberOfDeluxe.setText(String.valueOf(deluxeChoosed));
            lblTotalDeluxePrice.setText(String.valueOf(totalDeluxePrice));
            lblTotalPriceDetails.setText(String.valueOf(totalPriceDetails));
            if(presidentialChoosed==0){
                panelPresidentialPriceDetails.setVisible(false);
            } else {
                panelPresidentialPriceDetails.setVisible(true);
            }   
            if(deluxeChoosed==0){
                panelDeluxePriceDetails.setVisible(false);
            } else {
                panelDeluxePriceDetails.setVisible(true);
            }
            
            jPanelSlider.nextPanel(10, panel3, jPanelSlider.left);    
        }    
    }//GEN-LAST:event_btnNext2ActionPerformed

    private void btnPrev3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrev3ActionPerformed
        jPanelSlider.nextPanel(10, panel2, jPanelSlider.right);
    }//GEN-LAST:event_btnPrev3ActionPerformed

    private void btnNext3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext3ActionPerformed
        jPanelSlider.nextPanel(10, panel4, jPanelSlider.left);
    }//GEN-LAST:event_btnNext3ActionPerformed

    private void btnPrev4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrev4ActionPerformed
        jPanelSlider.nextPanel(10, panel3, jPanelSlider.right);
    }//GEN-LAST:event_btnPrev4ActionPerformed

    private void btnNext4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext4ActionPerformed
        if(tbFirstName.getText().trim().isEmpty() || 
                tbLastName.getText().trim().isEmpty() ||
                tbNoId.getText().trim().isEmpty() ||
                tbEmail.getText().trim().isEmpty() ||
                tbPhoneNo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please complete your information");
        } else 
        if(!tbEmail.getText().contains("@")){
            JOptionPane.showMessageDialog(null, "Your email does not correct");
        } else
        {
            lblGuest.setText(tbFirstName.getText()+" "+tbLastName.getText());
            lblEmail.setText(tbEmail.getText());
            lblCheckin.setText(checkInDate);
            lblCheckout.setText(checkOutDate);
            if(presidentialChoosed!=0 && deluxeChoosed!=0){
                lblRoomDetails.setText("<html>Presidential      x"+ presidentialChoosed + " room(s)<br/>"
                        + "Deluxe      x"+ deluxeChoosed +" room(s)</html>");
            }            
            if(deluxeChoosed==0){
                lblRoomDetails.setText("<html>Presidential      x"+ presidentialChoosed + " room(s)</html>");                        
            }
            if(presidentialChoosed==0){
                lblRoomDetails.setText("<html>Deluxe            x"+ deluxeChoosed + " room(s)</html>");                        
            }
            lblTotalPrice.setText(String.valueOf(totalPriceDetails));
           
            jPanelSlider.nextPanel(10, panel5, jPanelSlider.left);
            
        }
        
    }//GEN-LAST:event_btnNext4ActionPerformed

    private void btnPrev5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrev5ActionPerformed
        jPanelSlider.nextPanel(10, panel4, jPanelSlider.right);
    }//GEN-LAST:event_btnPrev5ActionPerformed

    private void btnNext5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext5ActionPerformed
        jPanelSlider.nextPanel(10, panel6, jPanelSlider.left);
    }//GEN-LAST:event_btnNext5ActionPerformed

    private void btnPrev6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrev6ActionPerformed
        jPanelSlider.nextPanel(10, panel5, jPanelSlider.right);
    }//GEN-LAST:event_btnPrev6ActionPerformed

    private void btnTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferActionPerformed
        jPanelSlider.nextPanel(10, panelTransfer1, jPanelSlider.left);
    }//GEN-LAST:event_btnTransferActionPerformed

    private void btnCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditActionPerformed
        jPanelSlider.nextPanel(10, panelCreditCard1, jPanelSlider.left);
    }//GEN-LAST:event_btnCreditActionPerformed

    private void btnPrevTransfer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevTransfer1ActionPerformed
        jPanelSlider.nextPanel(10, panel6, jPanelSlider.right);
    }//GEN-LAST:event_btnPrevTransfer1ActionPerformed

    private void btnBCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBCAActionPerformed
//        bankAccount = 1;
        jPanelSlider.nextPanel(10, panelTransfer2, jPanelSlider.left);
        lblBankAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon-bank-bca100.png"))); // NOI18N
        lblBankAccount.setText("Bank Central Asia");
        lblAccountNumber.setText("2821 464 988");
        lblAccountNumber1.setText("2821 464 988");
        lblAmount.setText(lblTotalPrice.getText());
    }//GEN-LAST:event_btnBCAActionPerformed

    private void btnBNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBNIActionPerformed
//        bankAccount = 2;
        jPanelSlider.nextPanel(10, panelTransfer2, jPanelSlider.left);
        lblBankAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon-bank-bni100.png"))); // NOI18N
        lblBankAccount.setText("Bank Nasional Indonesia");
        lblAccountNumber.setText("1140 0108 81145");
        lblAccountNumber1.setText("1140 0108 81145");
        lblAmount.setText(lblTotalPrice.getText());        
    }//GEN-LAST:event_btnBNIActionPerformed

    private void btnMandiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMandiriActionPerformed
//        bankAccount = 3;
        jPanelSlider.nextPanel(10, panelTransfer2, jPanelSlider.left);
        lblBankAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon-bank-mandiri100.png"))); // NOI18N
        lblBankAccount.setText("Bank Mandiri");
        lblAccountNumber.setText("1010 00480 2482");
        lblAccountNumber1.setText("1010 00480 2482");
        lblAmount.setText(lblTotalPrice.getText());   
    }//GEN-LAST:event_btnMandiriActionPerformed

    private void btnPrevTransfer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevTransfer2ActionPerformed
       jPanelSlider.nextPanel(10, panelTransfer1, jPanelSlider.right);
    }//GEN-LAST:event_btnPrevTransfer2ActionPerformed

    private void btnPrevCredit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevCredit1ActionPerformed
        jPanelSlider.nextPanel(10, panel6, jPanelSlider.right);
    }//GEN-LAST:event_btnPrevCredit1ActionPerformed

    private void btnNextCredit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextCredit1ActionPerformed
        viaCredit = true;
    }//GEN-LAST:event_btnNextCredit1ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        viaTransfer = true;
        controllerReservasi.insertReservasi();
        jPanelSlider.nextPanel(10, panelDone, jPanelSlider.left);
    }//GEN-LAST:event_button1ActionPerformed

    private void btnPrev7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrev7ActionPerformed
        jPanelSlider.nextPanel(10, panel1, jPanelSlider.right);
    }//GEN-LAST:event_btnPrev7ActionPerformed

    private void tbFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbFirstNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    // End of variables declaration//GEN-END:variables
}
